name: Deploy Next.js stand-alone to Azure Web App

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: '20'              # match the App Service runtime

    - run: npm ci                      # reproducible install
    - run: npm run build

    # -------- package the stand-alone output --------
    - run: |
        mkdir deploy
        cp -r .next/standalone/* deploy/
        cp -r .next/static deploy/.next/
        cp -r public deploy/
        cp next.config.js deploy/
        # Quick health probe
        echo 'console.log("package ready")' > deploy/healthcheck.js

    - run: |
        cd deploy && zip -r ../artifact.zip .
      shell: bash

    # -------- deploy --------
    - uses: azure/webapps-deploy@v2
      with:
        app-name: moss-mom
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: artifact.zip 